### ISSUE TITLE
Generic_M2O update issue

### ISSUE THREAD

**Issue by Tecnico1** [crnd-inc/generic-addons#1]
With the Generic_M2O module, the first time you select the value in the combo box, the widget acts as expected. But when you save the record and reopen it and try to select another value, the combo box does not update the new value until you close and save the form. Could you fix this problem?

I am working with version 12.0 but the same behavior occurs with version 13.0

Best regards

**Comment by katyukha** [comment]
Hi,

Thanks for this bug report.

We will try to fix it as soon as we have more time.

Thanks.

**Comment by Tecnico1** [comment]
Could you check the issue?

Best regards

**Comment by katyukha** [comment]
Hi @Tecnico1 

It seems that wehave fixed this bug. Please, check if it was fixed in your case.

Thanks)

**Comment by katyukha** [comment]
Issue seems to be solved, so closing.
