### ISSUE TITLE
Module operation error - generic-mixin

### ISSUE THREAD

**Issue by zalei-odoo** [crnd-inc/generic-addons#4]
Greetings. For the 2nd day I have been trying to configure the **generic-mixin** module to auto-update views in the **odoo16** branch.
At the moment, I had to disable auto-refresh when creating a record - I patched the GenericMixinRefreshView.create = create method, because immediately after creating a record, the page of the user who created the record is **automatically updated with the output of a new form for creating a new object**. For the write method, also when auto-update is triggered, a form is returned to create a new record. I found out that **the problem disappears if the page is refreshed manually**.
Tried various methods from the generic-mixin: it always works the same (the first time when the auto-refresh method is triggered, if the page has not been manually updated, the form is returned to create a new model entry) - with both _auto_refresh_view_on_write=True and trigger_refresh_view(action='write') )
**Is it possible to fix this bug, or advice, please?**

**Comment by katyukha** [comment]
Hi,

Thanks for reporting this issue)

Please, check the latest version of generic_mixin. It seems that this bug have to be fixed.

**Comment by zalei-odoo** [comment]
Thank you!!! Super, you are a real programmer!!! I enjoy your module.

**Comment by katyukha** [comment]
Seems to be fixed.
