### ISSUE TITLE
Suggestion for generic-mixin module

### ISSUE THREAD

**Issue by zalei-odoo** [crnd-inc/generic-addons#5]
Greetings. I want to suggest improving the functionality of the **generic-mixin** module. Faced the problem that in odoo16 (probably in other versions of odoo) when updating the form view, the pdf display (*<field name="attachment_pdf" widget="pdf_viewer"/>*) is not updated. Those. if you change the data in the *attachment_pdf* field in the table corresponding to the class inherited from *models.Model* (in case *attachment=False*), or if you change the data in the _'datas'_ field in the table corresponding to the _ir.attachment_ module - display the content of _pdf_ is not updated (I tried to change this field with a python script, from a cron task), _attachment_pdf_ is updated only if a new ir.attachment entry is created for the attachment-pdf field:
```
            self.env['ir.attachment'].create({
               'name': name,
               'type': 'binary',
               'res_field': 'attachment_pdf',
               'datas': b64_pdf,
               'store_fname': name,
               'res_model': self._name,
               'res_id': self.id,
               'mimetype': 'application/pdf'
            })
```
    Is it possible to complete the **generic-mixin** module to update the _iframe_ generated to display the pdf document:
`<iframe class="o_pdfview_iframe" alt="PDF-файл" src="/web/static/lib/pdfjs/web/viewer.html?file=http%3A%2F%2Flocalhost%3A8069%2Fweb%2Fcontent%3Fmodel%3Dtest_model%26field%3Dattachment_pdf%26id%3D3#page=1" name="attachment_pdf"></iframe>`?

**Comment by katyukha** [comment]
Hi,

For special cases, you can trigger refresh of view programmatically - just call [trigger_refresh_view](https://github.com/crnd-inc/generic-addons/blob/13.0/generic_mixin/models/generic_mixin_refresh_view.py#L188) method on model, and it will send command to refresh view for provided records.

There is no easy way to automatically handle all possible cases when part of data updated.

**Comment by zalei-odoo** [comment]
Thanks for the answer. I understand that it is possible to call [trigger_refresh_view](https://github.com/crnd-inc/generic-addons/blob/13.0/generic_mixin/models/generic_mixin_refresh_view.py#L188), but the update is not happening inside the iframe tag in the form view.
 To get the result, we need to call additionally js-script on clients with opened form, I think it's like this?
```
const pdf_views = document.querySelectorAll("iframe.o_pdfview_iframe");
for (let i = 0; i < pdf_views.length; i++) {
  pdf_views[i].contentWindow.location.reload(true);
}
```

**Comment by katyukha** [comment]
The view refresher is designed in the way, when it just asks controller to reload view (notifies that data was updated), and all next is responsibility of standard Odoo code to properly reload view. Thus, possibly it is bug in pdf viewer widget, that it do not handle the update of data properly.

**Comment by zalei-odoo** [comment]
Thanks for the answer. I agree with you, can close the issue.
